services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: zigma96
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employees
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  employee-server:
    image: chamikaravinda/employee-server:latest
    container_name: employee-server
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      USER: zigma96
      HOST: postgres
      DB: employees
      DB_PASSWORD: password
    networks:
      - employee
      - postgres
    depends_on:
      - postgres

  employee-client:
    image: chamikaravinda/employee-client:latest
    container_name: employee-client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5000"
    networks:
      - employee
    depends_on:
      - postgres 
      - employee-server   
networks:
  postgres:
    driver: bridge
  employee:
    driver: bridge

volumes:
  postgres:
  pgadmin:
# pg admin master password :password
