import Head from 'next/head';
import styles from '@/styles/Index.module.css'
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import { Link } from '@mui/material';

export default function Home() {

  return (
    <>
      <Head>
        <title>Employee Manager | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className={styles.banner}>
          <Typography variant="h2" className={styles.bannerHeading}>Welcom to Employee Manager</Typography>
          <Typography variant="h5">
            An employee manager is responsible for leading a team 
            to success. They provide support, guidance, and oversee
            performance to ensure a positive work environment and
            successful outcomes.
          </Typography>
          <Link href='employee/list'>
            <Button variant="contained" className={styles.btn}>
              Employees
            </Button>
          </Link>
          <Link href='employee/add'>
            <Button variant="outlined" className={styles.btn}>
              Add New
            </Button>
          </Link>
        </div>
      </main>
    </>
  )
}
