import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Button from '@mui/material/Button';
import AppsIcon from '@mui/icons-material/Apps';
import { Grid } from '@mui/material'



export default function Home() {
  return (
    <>
      <Head>
        <title>Employee Manager | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Grid container spacing={2}>
          <Grid lg={10}>
          </Grid>
          <Grid lg={2}>
          <Button variant="contained" className={styles.btnAddEmployee}>Add Employee</Button>
          <Button variant="contained" className={styles.btnViewType}>
            <AppsIcon/>
          </Button>
          </Grid>
        </Grid>
      </main>
    </>
  )
}
