import Head from 'next/head'
import styles from '@/styles/Employee.List.module.css'
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import FormatListBulletedIcon from '@mui/icons-material/FormatListBulleted';
import AppsIcon from '@mui/icons-material/Apps';
import { Grid } from '@mui/material'
import { useSelector } from "react-redux";
import React, { useState } from 'react';
import CommonTable from './../../components/table';
import ImageGrid from './../../components/grid';
import config from './../../config/index.config.json';
import { Link } from '@mui/material';
import { useRouter } from "next/router";

export default function EmployeeList() {
  
  const router = useRouter()
  
  const [isGrid, setIsGrid] = useState(false);
  const { users } = useSelector((state) => state.users);

  function toggleView () {
    setIsGrid(!isGrid);
  }

  function EditEmployee(id){
    router.push('/employee/edit/'+id);
  }

  function deleteEmployee(id){
    console.log("deleteAction")
  }

  return (
    <>
      <Head>
        <title>Employee Manager | List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Grid container spacing={2}>
          <Grid lg={10}>
          </Grid>
          <Grid lg={2}>
          <Link href="/employee/add">
            <Button variant="contained" className={styles.btnAddEmployee}>Add Employee</Button>
          </Link>
          <IconButton  
            variant="contained" 
            className={styles.btnViewType} 
            onClick={toggleView}
          >
            {
              isGrid ? <FormatListBulletedIcon/>: <AppsIcon/>
            }
          </IconButton >
          </Grid>
          <Grid xs={12}>
            {isGrid ? <ImageGrid 
                        data={users} 
                        editAction={EditEmployee} 
                        deleteAction={deleteEmployee}
                      /> : <CommonTable 
                          data={users} 
                          columns = {config.table_columes}
                          editAction={EditEmployee} 
                          deleteAction={deleteEmployee} 
                      /> 
              }
          </Grid>
        </Grid>
      </main>
    </>
  )
}
